import turtle
import time
a = turtle.Turtle()
p = turtle.Screen()
p.screensize(canvwidth=800, canvheight=800)
p.bgcolor("black")
n = 10 # distance to forward
z = 6 # width of pen.
s = 20 #speed of pen.
#a.penup()
#a.goto(0,0)
#a.down()
#a.color("white")
#a.write("HARSHIT",font=("monospace",15,"bold"))
#time.sleep(3)
h = -300
a.penup()
a.goto(h,0)
a.pendown()
a.speed(500)
def color():
	a.color("red")
	a.width(z)
	a.forward(n)
	a.color("orange")
	a.width(z)
	a.forward(n)
	a.color("yellow")
	a.width(z)
	a.forward(n)
	a.color("green")
	a.width(z)
	a.forward(n)
	a.color("blue")
	a.width(z)
	a.forward(n)
	a.color("indigo")
	a.width(z)
	a.forward(n)
	a.color("violet")
	a.width(z)
	a.forward(n)
	a.left(90)
	a.color("red")
	a.width(z)
	a.forward(n)
	a.color("orange")
	a.width(z)
	a.forward(n)
	a.color("yellow")
	a.width(z)
	a.forward(n)
	a.color("green")
	a.width(z)
	a.forward(n)
	a.color("blue")
	a.width(z)
	a.forward(n)
	a.color("indigo")
	a.width(z)
	a.forward(n)
	a.color("violet")
	a.width(z)
	a.forward(n)
	a.left(90)
	a.color("red")
	a.width(z)
	a.forward(n)
	a.color("orange")
	a.width(z)
	a.forward(n)
	a.color("yellow")
	a.width(z)
	a.forward(n)
	a.color("green")
	a.width(z)
	a.forward(n)
	a.color("blue")
	a.width(z)
	a.forward(n)
	a.color("indigo")
	a.width(z)
	a.forward(n)
	a.color("violet")
	a.width(z)
	a.forward(n)
	a.left(90)
	a.color("red")
	a.width(z)
	a.forward(n)
	a.color("orange")
	a.width(z)
	a.forward(n)
	a.color("yellow")
	a.width(z)
	a.forward(n)
	a.color("green")
	a.width(z)
	a.forward(n)
	a.color("blue")
	a.width(z)
	a.forward(n)
	a.color("indigo")
	a.width(z)
	a.forward(n)
	a.color("violet")
	a.width(z)
	a.forward(n)
	a.penup()
	a.goto(h,0)
	a.pendown()
while True:
	color()
	a.left(90)
	n+=5
	h +=10
	if h==-100:
		h= -300
		a.right(90)
		n = 10
		continue;
	