import turtle
p = turtle.Turtle()
z = turtle.Screen()
z.bgcolor("black")
p.width(4)
p.color("black")
p.fillcolor("cyan")
p.begin_fill()
p.circle(200)
p.end_fill()
p.fillcolor("white")
p.begin_fill()
p.circle(160)
p.end_fill()
p.penup()
p.goto(-22,140)
p.pendown()
p.fillcolor("red")
p.begin_fill()
for i in range(3):
	p.forward(40)
	p.right(-120)
p.end_fill()
